### PR TITLE
Fixes #1

### LINKED ISSUE #1: Add --nocdn flag to readme2tex, to support private repos and different branches
This app does not work on private repos or other branches, because it produces rawgit.com links, which require public access to the images on the master branch. With readme2tex's --nocdn flag, this shouldn't be a problem, as GitHub itself will handle the image delivery.

### PR DESCRIPTION
**Pull request by agurod42**

### CODE REVIEW

File: src/texify.js [hunk 1]
```diff
@@ -109,8 +111,13 @@ TeXify.prototype.renderTexFile = function (file) {
                         console.log(stdout)
 
                         try {
-                            let svgBaseUrl = urljoin(this.push.repository.html_url, '/master/').replace('github.com', 'rawgit.com')
-                            fs.writeFileSync(tmpOutputPath, fs.readFileSync(tmpOutputPath, 'utf8').replace(new RegExp(this.treeLocalPath, 'g'), svgBaseUrl))
+                            let svgBaseUrl = urljoin(this.push.repository.html_url, '/master/').replace('://github.com', '://raw.githubusercontent.com')
+
+                            let tmpOutputContents = fs.readFileSync(tmpOutputPath, 'utf8')
+                                .replace(new RegExp(this.treeLocalPath, 'g'), svgBaseUrl)
```
Comment (c-harding) [inline src/texify.js:117]: What's the point of doing this at all? Do relative links not work? This is enforcing using the master branch's version of the rendered tex, which may not exist

Comment (agurod42) [reply src/texify.js:117]: You're totally right. We should use relative urls. Gonna open a new issue
